### ISSUE TITLE
Unhelpful Policy Reporter Metrics 

### ISSUE THREAD

**Issue by EFX-PXT1** [hardbyte/netchecks#99]
Hi,

Uncertain if this is user error.

Cluster which includes kyverno policy-reporter to make available metrics.
If there is a failed test the policy report includes that failure in the history
with the timestamp of when the failure occurred.
There was a subsequent test which passed which is also present in the history.

The metrics seem to include any failures in the history rather than being
metrics for the most recent tests. And as a result the policy-report-ui dashboard
and the Grafana dashboards make it appear failures are present when they no longer are.

My expectation was that I would see metrics track last state when scraped by Prometheus.

To be clear the policy_report_summary metrics appear correct, but the policy_report_result
includes the historic failures.

Appreciate any guidance.

**Comment by hardbyte** [comment]
There might be some confusion between Prometheus metrics that netchecks emits (e.g. `netchecks_operator_assertion_processing_seconds`) and what the Kyverno Policy Reporter emits. 

Also I'm fairly sure the Kyverno UI is driven directly off the `PolicyReport` CRD resources (although I could very well be mistaken here). That said, I think both what netchecks is putting into the PolicyReport results, and storing as prometheus metrics could be improved. 

I suspect that the Kyverno Reporter UI assumes that there should be either multiple `PolicyReports` rather than multiple results to represent tests through time, or just a full replacement with the current results.

https://docs.google.com/document/d/1nICYLkYS1RE3gJzuHOfHeAC25QIkFZfgymFjgOzMDVw/edit?pli=1#heading=h.wn242twwl364 is the original proposal if you can see any clues.

p.s. Keep the feedback coming - its most appreciated.

**Comment by hardbyte** [comment]
Latest version of netchecks now complies with the design of Kyverno Policy Reporter - by replacing results in existing `PolicyReport` resources instead of appending to them.

Confirmed [here](https://github.com/kubernetes-sigs/wg-policy-prototypes/issues/134).
